# Generated by Django 4.1.5 on 2023-02-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVeterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='esta_castrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='esta_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='esta_recibido',
            field=models.BooleanField(default=False),
        ),
    ]
