# Generated by Django 4.1.5 on 2023-02-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVeterinaria', '0002_alter_paciente_esta_castrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='esta_castrado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='esta_activo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='esta_recibido',
            field=models.BooleanField(),
        ),
    ]
